-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Sep 15, 2023 at 10:03 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `diet`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `image` varchar(200) NOT NULL,
  `image2` varchar(200) NOT NULL,
  `image3` varchar(200) NOT NULL,
  `image4` varchar(200) NOT NULL,
  `cat` varchar(200) NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` mediumtext NOT NULL,
  `price` mediumtext NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `image`, `image2`, `image3`, `image4`, `cat`, `title`, `description`, `price`) VALUES
(1, 'https://i.ibb.co/n7Ktrp3/71-H28d2-Pf-AL-SX679-PIbundle-12-Top-Right-0-0-AA679-SH20.jpg', 'https://i.ibb.co/6Jd4f8D/81i-C0-L4-0-L-SX679.jpg', 'https://i.ibb.co/rvGL4ZF/71pf-KOm47-CL-SX679.jpg', 'https://i.ibb.co/dB1bWcG/71br-g7-EBl-L-SX679.jpg', 'lose', 'Premier Protein Shake, Vanilla, 30g Protein, 1g Sugar, 24 Vitamins & Minerals, Nutrients to Support Immune Health 11.5 Fl Oz (Pack of 12)', 'Introducing our delectable Vanilla flavor that evokes the nostalgia of classic vanilla wafers. This delightful winner of the American Masters of Taste Gold Medal offers a host of benefits:\r\n\r\nA substantial 30g of protein to tame your mid-day hunger or aid in post-workout recovery. It includes all the essential amino acids for a well-rounded protein source.\r\n\r\nBoost your overall health with a rich blend of 24 essential vitamins and minerals. It fortifies your immune system with antioxidant vitamins C, D, and E, along with Zinc and Magnesium. Plus, it provides 50% of your daily calcium requirement to support strong bones.\r\n\r\nA guilt-free indulgence awaits you with this low-fat shake. It contains only 1g of sugar, 4g of carbs, and a mere 160 calories. It\'s also Keto-friendly for those watching their carb intake.\r\n\r\nExplore a variety of eleven (11) luscious, smooth, and creamy flavors. Choose from Chocolate, Vanilla, Caramel, Cookies & Cream, Cafe Latte, Strawberries & Cream, Peaches & Cream, Bananas & Cream, Cinnamon Roll, Chocolate Peanut Butter, and Cake Batter Delight.\r\n\r\nBid farewell to the hassle of preparing protein powder. Our ready-to-drink protein shake offers ultimate convenience, perfect for your busy lifestyle. It\'s a great on-the-go nourishment option that also pairs wonderfully with coffee, cereal, pancake recipes, or your favorite smoothie.\r\n\r\nPlease note that this product contains Milk and Soy.\r\n\r\nEmbrace the deliciousness and convenience of our Vanilla protein shake, and experience a classic taste with modern nutritional benefits.', '42.99'),
(2, 'https://i.ibb.co/kMyLwYD/71ai4-Gs-Flx-L-AC-SX679.jpg', 'https://i.ibb.co/C0CRvGJ/91-TLJYP-rz-L-AC-SX679.jpg', 'https://i.ibb.co/0JPJGzw/81e-B9-Cmxd-ZL-AC-SX679.jpg', 'https://i.ibb.co/2Mpwx4k/81-IOi-ABq-T6-L-AC-SX425.jpg', 'lose', 'Garden of Life Organic Vegan Vanilla Protein Powder 22g Complete Plant Based Raw Protein', 'WHAT’S THE SCOOP: Rebuild broken muscle and reduce recovery time with 22g of complete plant-based protein and 4g of a complete branched chain amino acid profile; But that’s not all—stay satiated longer with 5g of fiber in just 130 calories per serving\r\nDOWNRIGHT DELICIOUS: We’re taking a stand against chalky and bringing tasty back; Not only is Raw Organic Protein now easy to mix and silky smooth, but our Vanilla Flavor is downright delicious; Mix with water, blend in smoothies or add in to baked goods\r\nSHAKE IT UP: Raw Organic Protein has been shaken up to improved texture and mixability all while being sugar free; Organic peas, sprouted grains, seeds, legumes plus whole food vitamins and minerals deliver nutrients you need with 1g total net carbs\r\nDON’T TAKE THE HEAT: Made at low temperatures, Raw Organic Protein is anything but ordinary; Scoop up digestive enzymes like lipase, lactase and papain plus live probiotics including probiotic Bacillus subtilis DE111 for digestion and proper absorption\r\nEXTRAORDINARY STANDARD – Raw Organic Protein is not only downright delicious but also provides clean Third-Party Certified nutrition—Certified USDA Organic, Non-GMO Project Verified, Certified Vegan, Kosher, NSF Certified Gluten Free & Contents Certified\r\nNote: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.', '79.99'),
(3, 'https://i.ibb.co/rdyc25P/71-XNW-Tfy5-L-AC-SX300-SY300-QL70-FMwebp.webp', 'https://i.ibb.co/7gh24fx/71-Hi7kt-Bu-HL-AC-SX679.jpg', 'https://i.ibb.co/tqv2DqF/71-AI-59-SLx-L-AC-SY879.jpg', 'https://i.ibb.co/rdyc25P/71-XNW-Tfy5-L-AC-SX300-SY300-QL70-FMwebp.webp', 'gain', 'Ultimate Nutrition Muscle Juice 2544, Lean Muscle Mass Classic ', 'MULTIPLE SOURCES OF PROTEIN: A protein blend that helps to supply 4 vital proteins - whey protein isolate, whey protein concentrate, calcium caseinate, and egg white albumen. This formula provides protein that helps to constantly feed and nourish your muscles.\r\nA WHOLESOME WEIGHT GAINER: Muscle Juice 2544 is a wholesome weight gainer that helps to supplement your regular workout. It has 55 grams of good quality protein per serving. It is a way to add the extra peptide–bonded and free-form amino acids to your nutrition program.\r\nLOOKING FOR MORE: This iso protein powder contains more ingredients such as Maltodextrin, Crystalline Fructose, Medium Chain Triglyceride or MCT, and Soy Lecithin. MCT allows for a slow and steady release of energy and helps to control serum cholesterol levels.\r\nOPTIMUM SOURCE OF AMINOS: This powder has over 26 grams of essential amino acids. Amino acids are one of the major building blocks of muscle development and are helpful for muscle tissue. This supplement helps to increase the anabolic environment and helps to stop muscle breakdown.\r\nCRAVE-WORTHY FLAVORS: 5 delicious flavors like Chocolate, Banana, Strawberry, Vanilla, and Cookies N Cream to make a delectable drink for you before or after the workout. Each shake mixes up effortlessly using just a glass and spoon and tastes consistently good, shake after shake.\r\nNote: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.', '74.99'),
(4, 'https://i.ibb.co/C8sPYVM/51m-P7vs16-TL-AC-SX300-SY300-QL70-FMwebp.webp', 'https://i.ibb.co/193dxF9/71-Ngq-Btbp0-L-AC-SX679.jpg', 'https://i.ibb.co/crYscpH/61-NPPPDbz-LL-AC-SX679.jpg', 'https://i.ibb.co/1KgBcRG/61-Zmc-Qku5-EL-AC-SX679.jpg', 'gain', 'Garden of Life Organic Vegan Sport Protein Powder, Vanilla', 'Organic sport protein: Certified USDA organic, Non-GMO project verified, NSF certified for sport, informed choice for sport certified, vegan, gluten free, dairy free, soy free, no added sugars\r\nPost workout recovery: Our Garden of Life Vegan Protein helps you refuel & repair muscles after a hard workout with 30 grams of complete protein and over 5 grams BCAA amino acids, glutamine & glutamic acid\r\nRecovery drinks: This sport protein powder promotes faster recovery with an organic high antioxidant blend of organic tart cherries, organic apples, organic turmeric, organic gogi berries and organic blueberries\r\nImmune system support: This BCAAs amino acid powder contains 2 billion CFU probiotic blend to keep your immune system strong during training\r\nCertified clean: Breath easy knowing this vegan amino acid powder is clean and free of any banned substances\r\nNote: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.', '19.99'),
(5, 'https://i.ibb.co/XYNmKcV/51m-P7vs16-TL-AC-SX679.jpg', 'https://i.ibb.co/D7N8n07/71-Ngq-Btbp0-L-AC-SX679.jpg', 'https://i.ibb.co/kSmPgrf/61-NPPPDbz-LL-AC-SX679.jpg', 'https://i.ibb.co/3W3VKSm/61-Zmc-Qku5-EL-AC-SX679.jpg', 'lose', 'Garden of Life Organic Vegan Sport Protein Powder, Vanilla', 'Organic sport protein: Certified USDA organic, Non-GMO project verified, NSF certified for sport, informed choice for sport certified, vegan, gluten free, dairy free, soy free, no added sugars\r\nPost workout recovery: Our Garden of Life Vegan Protein helps you refuel & repair muscles after a hard workout with 30 grams of complete protein and over 5 grams BCAA amino acids, glutamine & glutamic acid\r\nRecovery drinks: This sport protein powder promotes faster recovery with an organic high antioxidant blend of organic tart cherries, organic apples, organic turmeric, organic gogi berries and organic blueberries\r\nImmune system support: This BCAAs amino acid powder contains 2 billion CFU probiotic blend to keep your immune system strong during training\r\nCertified clean: Breath easy knowing this vegan amino acid powder is clean and free of any banned substances\r\nNote: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.', '39.99'),
(6, 'https://i.ibb.co/wSTFwk4/71-r-09rkk-L-AC-SY300-SX300.jpg', 'https://i.ibb.co/0sHbXDQ/71-LSGZ-8-Wj-L-AC-SX679.jpg', 'https://i.ibb.co/WgC8ZwH/71s-PR-5h-T0-L-AC-SX679.jpg', 'https://i.ibb.co/DzbWWKw/61-Q1-PGkbx7-L-AC-SX679.jpg', 'lose', 'Skinny Blend - Best Tasting Protein Shake for Women - Slim Fast Weight Loss Shakes - Meal Replacement', 'Special Blend of 7 Proteins to Maximize Fat Loss and Decrease Appetite\r\nScientifically Formulated to Suppress your Appetite, Burn Fat, and Boost Metabolism\r\nSpeeds Weight Loss, Nourishes Your Muscles, and Gives You Energy\r\nAmazing Taste and Mixes Easily\r\n30 Skinny Blend Shakes per Bag\r\nNote: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.', '24.99'),
(7, 'https://i.ibb.co/GsGFqMP/71ojv-WRd7-TL-AC-SX300-SY300-QL70-FMwebp.webp', 'https://i.ibb.co/3dZ79C0/81oub-MH7ef-L-AC-SX679.jpg', 'https://i.ibb.co/VDp4WW0/81-K9-SDv-Prb-L-AC-SX679.jpg', 'https://i.ibb.co/Z2sf661/81-WLd-Me-Wa3-L-AC-SX679.jpg', 'lose', 'Labrada Nutrition Lean Body Hi-Protein Shake, Strawberry, ', 'ALL-IN-ONE MRP - Forget other supplement pills and powders - you get it all in Lean Body: concentrated nutrition in one delicious, easy-to-make shake\r\nAWARD WINNING TASTE - Lean Body is a 5-time winner of the American Culinary Institute\'s Gold Medal Taste Award.\r\nLEAN BODY contains 40g of fast-release and slow-release proteins, to give you a sustained flow of vital amino acids for faster muscle growth and increases in strength.', '19.99'),
(8, 'https://i.ibb.co/dGpPydr/810k-Ch-Pjl-IL-AC-SX300-SY300-QL70-FMwebp.webp', 'https://i.ibb.co/LR16wt7/61-HAwiq-Gb-UL-AC-SX679.jpg', 'https://i.ibb.co/wWYmrg2/71-GVZFtos-NL-AC-SX679.jpg', 'https://i.ibb.co/C5nhp2D/615z-N4-QHG0-L-AC-SX679.jpg', 'lose', 'Garden of Life Dr. Formulated Keto Fit Weight Loss Shake - Vanilla Powder', 'NO MATH, JUST MIX: Doctor Perlmutter formulated our Keto Fit Weight Loss Shake with Clinically Studied ingredients and perfectly balanced macronutrients in ratios that FIT right in with your ketogenic or paleo diet—70% Fat, 20% Protein and 10% Carbs\r\nBURN FAT & FIGHT CRAVINGS: When it comes to weight loss shakes for women and men, you want proven ingredients; Fit provides 450mg of Clinically Studied Organic Svetol Green Coffee Bean extract, 300mg of Organic Ashwagandha and 65mg of Organic Coffeeberry\r\nGRASS FED & SO DELICIOUS: Sourcing matters! Our delightfully creamy Keto shake provides 16g of fat and 10g of protein from Grass Fed Butter powder & Whey Protein isolate; Dairy cows are humanely raised on family farms, happily grazing in lush pastures\r\nPOSSIBILITIES PLUS PROBIOTICS: Take your keto smoothie or fat bomb recipes to the next level with this a buttery smooth, low carb Vanilla shake—or simply mix it with water; We\'ve also added 1.5 Billion CFU of Probiotics for digestion\r\nTRULY CLEAN AND GREEN: Our passion for purity means you don\'t have to settle for less than Third-Party Certified Non-GMO, NSF Gluten Free, Keto, Paleo Friendly, Truly Grass Fed and Kosher; We are proudly B Corp and Carbon Neutral Certified\r\nNote: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.', '29.99'),
(9, 'https://i.ibb.co/mt691kX/41-LZKmx4-FL-SY300-SX300.jpg', 'https://i.ibb.co/yPRn0sB/61w0kpd-Nrs-L-SX679.jpg', 'https://i.ibb.co/G3mbzFf/613-I-6ev-AHL-SX679.jpg', '', 'lose', 'GNC Lean Shake 25 - Girl Scout Thin Mints', 'GNC Total Lean Lean Shake 25 - Girl Scout Thin Mints: Packed With Protein, Fiber & Other Essential Nutrients Lean Shake 25 now available in Girl Scout Cookie inspired flavors! Officially licensed by Girl Scouts of the USA (GSUSA), a nonprofit. Girl Scouts\' licensing program powers life-changing experiences for girls. When hunger strikes, you can still satisfy it without compromising your weight loss goals.  Lean Shake 25 is a delicious meal replacement packed with protein, fiber and other\r\nWell balanced with high-quality protein & fiber\r\nFortified with 22 vitamins & minerals\r\nSuitable for a low-carb diet\r\nDelicious & healthy addition to your daily meal plan', '24.99'),
(10, 'https://i.ibb.co/pRSCw2D/719-NJav-LPL-AC-SY300-SX300.jpg', 'https://i.ibb.co/mFF8R0T/712hz-Qgz-FTL-AC-SX679.jpg', 'https://i.ibb.co/vHS5Vbd/713h-ABt4s3-L-AC-SX679.jpg', 'https://i.ibb.co/jgMwrvR/81-0b3-A1-Kf-L-AC-SX679.jpg', 'gain', 'Soy-Free Protein Bundle: 8LB Chocolate Naked Vegan Mass and Naked Creatine', 'ONLY FIVE INGREDIENTS: Pea Protein Powder, Organic Rice Protein Powder, Organic Maltodextrin (made from gluten free organic tapioca) Organic Coconut Sugar and Organic Cacao. Chocolate Naked Vegan Mass contains no artificial sweeteners, flavors, or colors and is GMO Free, Soy Free, Gluten Free, and Dairy Free with no rBGH or rBST.\r\nREAL CLEAN PROTEIN: Gain weight the right way with our lactose free weight gainer, which contains our premium Naked Pea and Naked Rice protein. Chocolate Naked Vegan Mass provides your body with the amino acids it needs to maintain protein synthesis and help you gain muscle when used with a weightlifting fitness routine.\r\nIDEAL FOR CHOCOLATE WEIGHT GAINER SHAKES: Our chocolate vegan mass gainer has a mild flavor profile so you can easily control what goes into your body and flavor as desired with fruit such as a banana or blueberries. For use by men or women that prefer a non dairy weight gainer.\r\nHIGHEST QUALITY: Naked Creatine is the highest grade creatine monohydrate supplement available.\r\nRAPID ABSORPTION: Pure creatine monohydrate allows for fast absorption which enhances gains, strength, and increases training capacity.', '56.78'),
(11, 'https://i.ibb.co/jRB87s2/71g-F2a-Lm3-GL-AC-SX300-SY300-QL70-FMwebp.webp', 'https://i.ibb.co/bWrCj4M/81-GFPHa3-Rb-L-AC-SX679.jpg', 'https://i.ibb.co/bz5wsmg/9114-KJ14vd-L-AC-SX679.jpg', 'https://i.ibb.co/df0b57C/71it-Qlibfg-L-AC-SX679.jpg', 'gain', 'Six Star Whey Protein Powder Whey Protein Plus Whey Protein Isolate', 'WHEY PROTEIN POWDER – Formulated with 30g of protein from ultra-pure 100% whey protein and an added immune support matrix, Six Star 100% Whey Protein Plus is the fuel you need after your workout or any time of day\r\nMUSCLE BUILDER for MEN & WOMEN – Six Star 100% Whey Protein Plus has 13.4g of total BCAAs per 2 scoops. BCAAs fuel your skeletal muscles during training, which can help give you the edge you need to push your limits\r\nIMMUNE SUPPORT – Six Star 100% Whey Protein Plus has an added immunity support matrix, including Vitamin C & Zinc, to help support your immune system\r\nPROTEIN POWDER for MUSCLE GAIN – Mix 1 serving (1 scoop) in 6 to 8 oz of water or skim milk, according to taste. For maximum effects take 2 servings daily\r\nNote: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.', '69.69'),
(12, 'https://i.ibb.co/TRFfMzJ/71-Vs-Ega-Ojz-L-AC-SX300-SY300-QL70-FMwebp.webp', 'https://i.ibb.co/jZSx34V/61-QOYtu7-m-L-AC.jpg', 'https://i.ibb.co/RCMrdkc/91w-Tz-Rw0l-L-AC-SX679.jpg', 'https://i.ibb.co/k2fSZ4H/61-Zs-IJ6y-KL-AC.jpg', 'gain', 'Muscle Milk Genuine Protein Powder, Chocolate,', 'Contains one (1) 1.93 pound cannister (about 12 servings) of Muscle Milk Genuine Protein Powder. Packaging may vary. Shaker bottle sold separately.\r\nHELPS SATISFY HUNGER AND BUILD MUSCLE – Muscle Milk Genuine Protein Powder supplies your body with high quality protein to support post-workout recovery and muscle growth. Or try taking it to-go in a shaker bottle for an energizing on-the-go breakfast.\r\nKEY FEATURES – Based on 1 serving, Muscle Milk Genuine Protein Powder contains 32g high-quality protein, 3g sugar, and an excellent source of Calcium and Vitamins A, C & D\r\nVERSATILE AND EASY-TO-MIX – Muscle Milk Genuine Protein Powder dissolves easily in water; just mix 2 scoops into 8 fluid ounces of water using a shaker bottle. Shaker bottle sold separately. Also add to recipes when you are looking for a protein boost.\r\nSCIENCE BEHIND PROTEIN – Muscle Milk Genuine provides a combination of high-quality slow releasing and fast releasing proteins to help increase amino acid levels. These essential amino acids play a role in muscle growth and maintenance of muscle mass.\r\nTESTED FOR BANNED SUBSTANCES – Muscle Milk Protein Powders are NSF Certified for Sport. NSF screens for more than 270 substances banned by most major athletic organizations.\r\nNote: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.', '56.74'),
(13, 'https://i.ibb.co/12YK1G3/41-ALSROn-YHL-SX300-SY300-QL70-FMwebp.webp', 'https://i.ibb.co/sQdB8pH/71-ev-Nv-Otn-L-SX679.jpg', 'https://i.ibb.co/YfgPt58/61-L5-SO58-Zw-L-SX679.jpg', 'https://i.ibb.co/x3BGNBF/71-GB32gyv-EL-SX679.jpg', 'gain', 'Evolve Protein Shake & Protein Powder Bundle, Chocolate', '20 GRAMS OF PLANT-BASED PROTEIN sourced from peas, a delicious and more sustainable source of protein\r\nNON-GMO PROJECT VERIFIED and made without artificial flavors or sweeteners and with no colors from artificial sources.Non-Caffeinated\r\nGOOD SOURCE OF calcium, iron, vitamin B12 and zinc, which are an important part of any diet, and are particularly important for those whose diets are light in, or lack, meat, eggs and dairy\r\nVEGETABLE-BASED AND PLANT POWERED PROTEIN - EVOLVE Protein Powder is a real plant powered protein source that provides 20g for protein for sustained energy to help support your active lifestyle\r\nGOOD. SIMPLE. PROTEIN. - EVOLVE Protein Powders are free of dairy, soy and gluten ingredients, are low in fat, and are free of artificial flavors\r\nCONVENIENT NUTRITION - EVOLVE Protein Powder is an ideal nutritional choice to complement your daily food choices. Food Form: Liquids', '23.23'),
(14, 'https://i.ibb.co/LzgXYmY/71mjo-Ui-Ne-BL-AC-SX300-SY300-QL70-FMwebp.webp', 'https://i.ibb.co/hBrW866/81w-Gns-Ox-PHL-AC-SX679.jpg', 'https://i.ibb.co/9pDKhwW/91-B-e7m-R-HL-AC-SX679.jpg', 'https://i.ibb.co/kSywvpk/71s0-LZlu-XQL-AC-SX679.jpg', 'gain', 'Ascent 100% Whey Protein Powder - Post Workout Whey Protein Isolate', 'Native Whey Protein Powder Isolate Blend - The least-processed chocolate whey protein available today, naturally higher in leucine for muscle synthesis. Mixes silky smooth every time with just cold water.\r\n25g Protein Per Scoop - 5.5g Naturally Occurring BCAAs, and a clean, minimalist ingredient list. Certified Gluten Free and Informed Choice Certified. Lightly sweetened with stevia leaf extract.\r\nDesigned for Post Workout Recovery - Supports fitness goals with pure whey that rapidly digests to fuel muscle growth and recovery. A protein smoothie essential.\r\n0g of Added Sugar, Zero Artificial Flavors and Sweeteners - Clean, pure protein that easily fits low carb and keto diets. Perfect for recipes & baking high protein snacks.\r\n2 LB Whey Protein Powder with included scoop - Simple collapsible bag packaging for easier storage in small or irregular cabinets and drawers.\r\nNote: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.', '54.67'),
(15, 'https://i.ibb.co/HHJzQsg/810k-Ch-Pjl-IL-AC-SX300-SY300-QL70-FMwebp-1.webp', 'https://i.ibb.co/rs0JQHp/61-HAwiq-Gb-UL-AC-SX679-1.jpg', 'https://i.ibb.co/0DFRsB8/71-GVZFtos-NL-AC-SX679-1.jpg', 'https://i.ibb.co/VxKVxWw/615z-N4-QHG0-L-AC-SX679-1.jpg', 'maintain', 'Garden of Life Dr. Formulated Keto Fit Weight Loss Shake', 'NO MATH, JUST MIX: Doctor Perlmutter formulated our Keto Fit Weight Loss Shake with Clinically Studied ingredients and perfectly balanced macronutrients in ratios that FIT right in with your ketogenic or paleo diet—70% Fat, 20% Protein and 10% Carbs\r\nBURN FAT & FIGHT CRAVINGS: When it comes to weight loss shakes for women and men, you want proven ingredients; Fit provides 450mg of Clinically Studied Organic Svetol Green Coffee Bean extract, 300mg of Organic Ashwagandha and 65mg of Organic Coffeeberry\r\nGRASS FED & SO DELICIOUS: Sourcing matters! Our delightfully creamy Keto shake provides 16g of fat and 10g of protein from Grass Fed Butter powder & Whey Protein isolate; Dairy cows are humanely raised on family farms, happily grazing in lush pastures\r\nPOSSIBILITIES PLUS PROBIOTICS: Take your keto smoothie or fat bomb recipes to the next level with this a buttery smooth, low carb Vanilla shake—or simply mix it with water; We\'ve also added 1.5 Billion CFU of Probiotics for digestion\r\nTRULY CLEAN AND GREEN: Our passion for purity means you don\'t have to settle for less than Third-Party Certified Non-GMO, NSF Gluten Free, Keto, Paleo Friendly, Truly Grass Fed and Kosher; We are proudly B Corp and Carbon Neutral Certified\r\nNote: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.', '14.98'),
(16, 'https://i.ibb.co/m4tzkGC/41-Tku-EX7h-NL-SX300-SY300-QL70-FMwebp.webp', 'https://i.ibb.co/qrfJGw9/71l5j-Dxza3-L-SX679.jpg', 'https://i.ibb.co/HFXQV2R/81r-Sao-BNn-SL-SX679.jpg', 'https://i.ibb.co/4fL3HM4/61-D-wv-Qe-MGL.jpg', 'maintain', 'Muscle Milk Chocolate 1.93 lbs', 'Protein Drink\r\nGreat Taste\r\nLeading Brand\r\n', '15.78'),
(17, 'https://i.ibb.co/Wsv90Sz/41zzl-XIe-Fc-L-SX300-SY300-QL70-FMwebp.webp', 'https://i.ibb.co/5ryGZhG/31u-DXOa-GSy-L.jpg', 'https://i.ibb.co/q1C2W6f/A1n-Sm-FTY-DL-SX569.jpg', '', 'maintain', 'Boost High Protein Complete Nutritional Drink, Very Vanilla, 8 fl. oz., 24 Count', 'Excellent source of calcium and vitamin D\r\n26 essential vitamins and minerals\r\n15g of high quality protein\r\nGluten free\r\nLactose Free', '56.78'),
(18, 'https://i.ibb.co/zGxGm9g/71s-Kwp-W7-f-L-AC-SX300-SY300-QL70-FMwebp.webp', 'https://i.ibb.co/rM9kwJ9/81bz-Wi-Yt5k-L-AC-SX679.jpg', 'https://i.ibb.co/nwD5KMK/51ifjk77x-CL-AC-SX679.jpg', 'https://i.ibb.co/YQ6cKvm/51-Kx-Q4-KC-L-AC.jpg', 'maintain', 'Ekopura Organic Casein Protein - Purely Natural - 78% Protein', 'High in protein (78%) for Optimal Recovery, Muscle Build and Muscle Retention. Dissolves perfectly in water or any other liquid.\r\nUse Organic Casein to secure optimal protein intake by the body during hours of the day without food ie. during your Sleep or a long Workday.\r\n100% Organic Casein protein powder form Happy Grass Fed Cows that can graze freely all year round. Hormone free, GMO free, Soy free, no Artificial Additives, no Added Sugars.\r\nIngredients: Organic Casein Protein Concentrate. Contains a complete Amino Acid profile (BCAA\'s). Allergens: contains lactose\r\nDelicious, Creamy and Neutral taste. Perfect as a before bedtime shake, to make delicious smoothies or as an addition to your breakfast or in between snack.\r\nNote: Products with electrical plugs are designed for use in the US. Outlets and voltage differ internationally and this product may require an adapter or converter for use in your destination. Please check compatibility before purchasing.', '53.2');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
